using System.ComponentModel;
using System.Text;

namespace DriverTests.Output;

[Collection ("Driver Tests")]
public class OutputFailureHandlingTests
{
    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (4)]
    [InlineData (11)]
    [InlineData (35)]
    public void UnixTransientFailure_RetriesExactUnwrittenTail (int error)
    {
        if (error != 4 && error != (OperatingSystem.IsMacOS () || OperatingSystem.IsFreeBSD () ? 35 : 11))
        {
            return;
        }

        List<string> tails = [];
        int calls = 0;
        bool success = UnixIOHelper.TryWriteAll (1, "ABC"u8, (_, bytes) =>
        {
            tails.Add (Encoding.UTF8.GetString (bytes));
            calls++;
            return calls == 2 ? -1 : 1;
        }, () => error);

        Assert.True (success);
        Assert.Equal (["ABC", "BC", "BC", "C"], tails);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (4)]
    [InlineData (5)]
    public void UnixRepeatedFailure_IsBounded (int error)
    {
        int calls = 0;
        Assert.False (UnixIOHelper.TryWriteAll (1, "A"u8, (_, _) => { calls++; return -1; }, () => error));
        Assert.Equal (error == 4 ? 9 : 1, calls);
    }

    // Claude - Opus 5.5
    [Fact]
    public void UnixTransientFailuresBetweenProgress_DoNotAbortWrite ()
    {
        List<byte> written = [];
        int calls = 0;

        // Every byte is preceded by EINTR: 32 interruptions in total, but never more than one in a row.
        bool success = UnixIOHelper.TryWriteAll (1, Encoding.UTF8.GetBytes (new string ('x', 32)), (_, bytes) =>
        {
            if (calls++ % 2 == 0)
            {
                return -1;
            }

            written.Add (bytes [0]);

            return 1;
        }, () => 4);

        Assert.True (success);
        Assert.Equal (32, written.Count);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false)]
    [InlineData (true)]
    public void AnsiDispose_AttemptsEveryRestoreAfterFailure (bool inline)
    {
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            writes.Add (Encoding.UTF8.GetString (bytes));
            return false;
        }, inline ? AppModel.Inline : AppModel.FullScreen) { AppScreenGetter = () => new (0, 3, 10, 2) };

        output.Dispose ();

        Assert.Contains (EscSeqUtils.CSI_DisableBracketedPaste, writes);
        Assert.Contains (EscSeqUtils.CSI_DisableMouseEvents, writes);
        Assert.Contains (EscSeqUtils.CSI_ResetAttributes, writes);
        Assert.Contains (EscSeqUtils.CSI_ShowCursor, writes);
        Assert.Contains (inline ? "\n" : EscSeqUtils.CSI_RestoreCursorAndRestoreAltBufferWithBackscroll, writes);
        Assert.Equal (inline ? 6 : 5, writes.Count);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void AnsiCursor_PositionFailureDoesNotEscapeFinally ()
    {
        int calls = 0;
        AnsiOutput output = new (_ => ++calls == 1);
        output.SetCursor (new () { Position = new (0, 0) });
        Assert.Equal (2, calls);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false)]
    [InlineData (true)]
    public void DriverRefresh_ContainsNativeErrorAndRetriesDirtyCells (bool windowsFailure)
    {
        bool fail = true;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                if (windowsFailure)
                {
                    throw new Win32Exception (5);
                }

                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");
        using DriverImpl driver = CreateDriver (output, buffer);

        driver.Refresh ();
        Assert.True (driver.NeedsOutputRetry);
        Assert.True (buffer.Contents! [0, 0].IsDirty);
        fail = false;
        driver.Refresh ();
        Assert.False (driver.NeedsOutputRetry);
        Assert.Contains ("X", Assert.Single (writes));
    }

    // Claude - Opus 5.5
    [Fact]
    public void ProgressIndicator_WriteFailure_DoesNotThrowAndRequestsRetry ()
    {
        AnsiOutput output = new (_ => false);
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        using DriverImpl driver = CreateDriver (output, buffer);
        ProgressIndicator indicator = new (driver);

        Exception? exception = Record.Exception (() => indicator.SetValue (50));

        Assert.Null (exception);
        Assert.True (driver.NeedsOutputRetry);
    }

    // Claude - Opus 5.5
    [Fact]
    public void ProgressIndicator_FailedWrite_IsRetried ()
    {
        bool fail = true;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));

            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        using DriverImpl driver = CreateDriver (output, buffer);
        ProgressIndicator indicator = new (driver);

        indicator.SetValue (50);
        fail = false;
        indicator.SetValue (50);

        Assert.Equal ([EscSeqUtils.OSC_SetProgressValue (50)], writes);
    }

    // Claude - Opus 5.5
    [Fact]
    public void ProgressIndicator_FailedClear_IsRetried ()
    {
        bool fail = false;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));

            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        using DriverImpl driver = CreateDriver (output, buffer);
        ProgressIndicator indicator = new (driver);
        indicator.SetValue (50);

        fail = true;
        indicator.Clear ();
        fail = false;
        indicator.Clear ();
        indicator.Clear ();

        Assert.Equal ([EscSeqUtils.OSC_SetProgressValue (50), EscSeqUtils.OSC_ClearProgress ()], writes);
    }

    // Claude - Opus 5.5
    [Fact]
    public void RepeatedOutputFailures_BackOffUntilRecovery ()
    {
        bool fail = true;
        AnsiOutput output = new (_ => !fail);
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");
        using DriverImpl driver = CreateDriver (output, buffer);

        driver.Refresh ();
        Assert.True (driver.IsOutputRetryDue);

        driver.Refresh ();
        Assert.True (driver.NeedsOutputRetry);
        Assert.False (driver.IsOutputRetryDue);

        fail = false;
        Assert.True (SpinWait.SpinUntil (() => driver.IsOutputRetryDue, TimeSpan.FromSeconds (5)));
        driver.Refresh ();
        Assert.False (driver.NeedsOutputRetry);
        Assert.False (driver.IsOutputRetryDue);

        fail = true;
        buffer.Move (0, 0);
        buffer.AddStr ("Y");
        driver.Refresh ();
        Assert.True (driver.IsOutputRetryDue);
    }

    // Claude - Opus 5.5
    [Fact]
    public void Refresh_DuringBackoff_DoesNotWriteUntilRetryIsDue ()
    {
        bool fail = true;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));

            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");
        using DriverImpl driver = CreateDriver (output, buffer);
        driver.Refresh ();
        driver.Refresh ();
        Assert.False (driver.IsOutputRetryDue);

        // A view that keeps redrawing must not bypass the backoff.
        fail = false;
        buffer.Move (0, 0);
        buffer.AddStr ("Y");
        driver.Refresh ();
        Assert.Empty (writes);
        Assert.True (driver.NeedsOutputRetry);

        Assert.True (SpinWait.SpinUntil (() => driver.IsOutputRetryDue, TimeSpan.FromSeconds (5)));
        driver.Refresh ();

        Assert.Contains ("Y", Assert.Single (writes));
        Assert.False (driver.NeedsOutputRetry);
    }

    // Claude - Opus 5.5
    [Fact]
    public void KittyKeyboardEnable_WriteFailure_DoesNotThrowAndRequestsRetry ()
    {
        AnsiOutput output = new (_ => false);
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        using DriverImpl driver = CreateDriver (output, buffer);
        KittyKeyboardProtocolDetector detector = new (driver);

        Exception? exception = Record.Exception (() => detector.Enable (EscSeqUtils.KittyKeyboardRequestedFlags));

        Assert.Null (exception);
        Assert.True (driver.NeedsOutputRetry);
    }

    // Claude - Opus 5.5
    [Fact]
    public void KittyKeyboardDisable_WriteFailure_DoesNotThrowAndRequestsRetry ()
    {
        AnsiOutput output = new (_ => false);
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        using DriverImpl driver = CreateDriver (output, buffer);
        KittyKeyboardProtocolDetector detector = new (driver);

        Exception? exception = Record.Exception (detector.Disable);

        Assert.Null (exception);
        Assert.True (driver.NeedsOutputRetry);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void DriverRefresh_ProgrammingErrorStillEscapes ()
    {
        AnsiOutput output = new (_ => throw new InvalidOperationException ("sink bug"));
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");
        using DriverImpl driver = CreateDriver (output, buffer);
        Assert.Throws<InvalidOperationException> (driver.Refresh);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void ApplicationDraw_RetriesPhysicalFailureWithoutAnotherViewDraw ()
    {
        using IApplication app = Application.Create ().Init (DriverRegistry.Names.ANSI);
        IDriver originalDriver = app.Driver!;
        bool fail = false;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (10, 2);
        using DriverImpl driver = CreateDriver (output, buffer);
        app.Driver = driver;
        using Runnable runnable = new () { Width = 10, Height = 2 };
        SessionToken owner = app.Begin (runnable)!;

        try
        {
            app.LayoutAndDraw ();
            writes.Clear ();
            buffer.Move (0, 0);
            buffer.AddStr ("RECOVER");
            fail = true;
            driver.Refresh ();
            Assert.True (driver.NeedsOutputRetry);
            Assert.False (runnable.NeedsDraw);
            Assert.False (runnable.SubViewNeedsDraw);
            fail = false;
            app.LayoutAndDraw ();
            Assert.False (driver.NeedsOutputRetry);
            Assert.Contains ("RECOVER", Assert.Single (writes));
        }
        finally
        {
            app.End (owner);
            app.Driver = originalDriver;
        }
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void WindowsConsole_PartialWritesUseOnlyRemainingCharacters ()
    {
        List<string> tails = [];
        StringBuilder received = new ();
        WindowsOutput.WriteConsoleChecked (0, "A😀中".AsSpan (), (nint _, ReadOnlySpan<char> text, out uint written, out int error) =>
        {
            tails.Add (text.ToString ());
            received.Append (text [0]);
            written = 1;
            error = 0;
            return true;
        });
        Assert.Equal ("A😀中", received.ToString ());
        Assert.Equal (["A😀中", "😀中", "\ude00中", "中"], tails);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false, 0, 0)]
    [InlineData (true, 0, 0)]
    [InlineData (true, 2, 0)]
    public void WindowsConsole_RejectsFailureAndInvalidProgress (bool success, uint count, int nativeError)
    {
        Assert.Throws<IOException> (() => WindowsOutput.WriteConsoleChecked (0, "X".AsSpan (),
            (nint _, ReadOnlySpan<char> _, out uint written, out int error) => { written = count; error = nativeError; return success; }));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void LegacyEncodingSink_DoesNotRecurseIntoItsOwnOverride ()
    {
        ForwardingLegacyOutput output = new () { CaptureOutput = true };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (3, 1);
        buffer.AddStr ("Ω中");
        output.Write (buffer);
        Assert.Equal (1, output.Calls);
        Assert.Contains ("Ω中", output.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void DisabledCapture_ClearsPreviousOutput ()
    {
        AnsiOutput output = new (_ => true) { CaptureOutput = true };
        output.Write ("secret".AsSpan ());
        Assert.Equal ("secret", output.GetLastOutput ());
        output.CaptureOutput = false;
        Assert.Empty (output.GetLastOutput ());
        output.Write ("ignored".AsSpan ());
        output.CaptureOutput = true;
        Assert.Empty (output.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void AnsiLargeText_ReusesBoundedEncodingAndPreservesSurrogateBoundaries ()
    {
        string payload = new string ('a', 16383) + "😀" + new string ('中', 1024 * 1024);
        StringBuilder received = new ();
        bool collect = false;
        AnsiOutput output = new (bytes =>
        {
            if (collect)
            {
                received.Append (Encoding.UTF8.GetString (bytes));
            }

            return true;
        }) { CaptureOutput = false };
        output.Write (payload.AsSpan ());
        long before = GC.GetAllocatedBytesForCurrentThread ();
        output.Write (payload.AsSpan ());
        long allocated = GC.GetAllocatedBytesForCurrentThread () - before;
        collect = true;
        output.Write (payload.AsSpan ());
        Assert.Equal (payload, received.ToString ());
        Assert.InRange (allocated, 0, 1024);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void PerCellColoredFrame_StreamsWithoutRepeatedMegabyteAllocations ()
    {
        int writes = 0;
        int bytesWritten = 0;
        int largestWrite = 0;
        AnsiOutput output = new (bytes =>
        {
            writes++;
            bytesWritten += bytes.Length;
            largestWrite = Math.Max (largestWrite, bytes.Length);
            return true;
        }) { CaptureOutput = false };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (400, 110);

        for (int row = 0; row < buffer.Rows; row++)
        {
            for (int col = 0; col < buffer.Cols; col++)
            {
                buffer.Move (col, row);
                buffer.CurrentAttribute = new (new Color (col % 256, row % 256, (row + col) % 256), Color.Black);
                buffer.AddRune ('A');
            }
        }

        output.Write (buffer);
        for (int row = 0; row < buffer.Rows; row++)
        {
            buffer.DirtyLines [row] = true;
            for (int col = 0; col < buffer.Cols; col++)
            {
                buffer.Contents! [row, col].IsDirty = true;
            }
        }

        writes = 0;
        bytesWritten = 0;
        largestWrite = 0;
        long before = GC.GetAllocatedBytesForCurrentThread ();
        output.Write (buffer);
        long allocated = GC.GetAllocatedBytesForCurrentThread () - before;
        Assert.True (writes >= 2);
        Assert.True (bytesWritten > Utf8Buffer.RetainedCapacityLimit);
        Assert.InRange (largestWrite, 1, Utf8Buffer.RetainedCapacityLimit);
        // GetColumns currently allocates per grapheme (~12 MB for this frame). Allow that
        // existing cost, but reject the additional ~4 MB from repeated oversized staging.
        Assert.InRange (allocated, 0, 14 * 1024 * 1024);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void InjectedAnsiConstructor_DoesNotReplaceProcessConsoleWriter ()
    {
        TextWriter before = Console.Out;
        using AnsiOutput output = new (_ => true);
        Assert.Same (before, Console.Out);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void ConcreteLegacyEncodingSinks_ForwardTextAndRasterOnce ()
    {
        int physicalWrites = 0;
        ForwardingAnsiOutput ansi = new (_ => { physicalWrites++; return true; }) { CaptureOutput = true };
        ForwardingNetOutput net = new () { CaptureOutput = true };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("Ω");
        ansi.GetSixels ().Enqueue (new () { SixelData = "IMAGE", ScreenPosition = new (0, 0) });
        ansi.Write (buffer);
        buffer.Move (0, 0);
        buffer.AddStr ("Ω");
        net.GetSixels ().Enqueue (new () { SixelData = "IMAGE", ScreenPosition = new (0, 0) });
        net.Write (buffer);
        Assert.Equal (2, ansi.Calls);
        Assert.Equal (2, physicalWrites);
        Assert.Equal (2, net.Calls);
        Assert.Contains ("Ω", ansi.GetLastOutput ());
        Assert.Contains ("IMAGE", ansi.GetLastOutput ());
        Assert.Contains ("Ω", net.GetLastOutput ());
        Assert.Contains ("IMAGE", net.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void FailedRawDriverWrite_ClosesUncertainControlStringOnNextRefresh ()
    {
        bool fail = true;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail) return false;
            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        using DriverImpl driver = CreateDriver (output, buffer);
        driver.WriteRaw ("\u001b]0;TITLE\u001b\\");
        Assert.True (driver.NeedsOutputRetry);
        fail = false;
        driver.Refresh ();
        Assert.StartsWith ("\u001b\\", Assert.Single (writes));
        Assert.False (driver.NeedsOutputRetry);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void WindowsVt_FailureWithoutErrorCodeIsStillAnIoFailure ()
    {
        WindowsVTOutputHelper output = new ((ReadOnlySpan<byte> _, out uint written, out int error) =>
        {
            written = 0;
            error = 0;
            return false;
        });
        Assert.Throws<IOException> (() => output.Write ("X"u8));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void DefaultByteSink_WithCaptureDisabled_DoesNotBuildDiscardedStrings ()
    {
        CaptureOnlyOutput output = new () { CaptureOutput = false };
        byte [] payload = new byte [1024 * 1024];
        output.WriteBytes (payload);
        long before = GC.GetAllocatedBytesForCurrentThread ();
        output.WriteBytes (payload);
        Assert.InRange (GC.GetAllocatedBytesForCurrentThread () - before, 0, 128);
        Assert.Empty (output.GetLastOutput ());
    }

    private static DriverImpl CreateDriver (AnsiOutput output, OutputBufferImpl buffer) => new (
        new AnsiComponentFactory (), new AnsiInputProcessor (null!), buffer, output,
        new (new AnsiResponseParser (new SystemTimeProvider ())), new SizeMonitorImpl (output));

    private sealed class CaptureOnlyOutput : OutputBase
    {
        protected override bool SetCursorPositionImpl (int screenPositionX, int screenPositionY) => true;
        public void WriteBytes (ReadOnlySpan<byte> bytes) => Write (bytes);
    }

    private sealed class ForwardingAnsiOutput (AnsiOutput.UnixWriter writer) : AnsiOutput (writer)
    {
        public int Calls { get; private set; }
        protected override bool SetCursorPositionImpl (int col, int row) => true;
        protected override void Write (StringBuilder output)
        {
            if (++Calls > 4) throw new InvalidOperationException ("recursive fallback");
            Write (Encoding.UTF8.GetBytes (output.ToString ()));
        }
    }

    private sealed class ForwardingNetOutput : NetOutput
    {
        public int Calls { get; private set; }
        protected override bool SetCursorPositionImpl (int col, int row) => true;
        protected override void Write (StringBuilder output)
        {
            if (++Calls > 4) throw new InvalidOperationException ("recursive fallback");
            Write (Encoding.UTF8.GetBytes (output.ToString ()));
        }
    }

    private sealed class ForwardingLegacyOutput : OutputBase
    {
        public int Calls { get; private set; }
        protected override bool SetCursorPositionImpl (int screenPositionX, int screenPositionY) => true;
        protected override void Write (StringBuilder output)
        {
            Calls++;
            if (Calls > 2)
            {
                throw new InvalidOperationException ("recursive fallback");
            }

            Write (Encoding.UTF8.GetBytes (output.ToString ()));
        }
    }
}
