using System.ComponentModel;
using System.Text;

namespace DriverTests.Output;

/// <summary>Verifies frame retry after I/O failure and compatibility with legacy output overrides.</summary>
[Collection ("Driver Tests")]
public class OutputRetryAndCompatibilityTests
{
    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void LegacyAttributeHook_CanFlushPreviouslyBufferedText ()
    {
        FlushingAttributeOutput output = new ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (2, 1);
        buffer.CurrentAttribute = new (new Color (1, 0, 0), Color.Black);
        buffer.AddStr ("A");
        buffer.CurrentAttribute = new (new Color (2, 0, 0), Color.Black);
        buffer.AddStr ("B");

        output.Write (buffer);

        Assert.Equal (["attribute:1", "text:A", "attribute:2", "text:B"], output.Events);
    }

    // Claude - Opus 5.5
    [Fact]
    public void LegacyAttributeHook_PerCellColors_AllocationIsLinear ()
    {
        AppendingAttributeOutput output = new ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (200, 50);

        for (var row = 0; row < 50; row++)
        {
            buffer.Move (0, row);

            for (var col = 0; col < 200; col++)
            {
                buffer.CurrentAttribute = new (new Color (col, row, (col + row) % 256), Color.Black);
                buffer.AddStr ("x");
            }
        }

        long before = GC.GetAllocatedBytesForCurrentThread ();
        output.Write (buffer);
        long allocated = GC.GetAllocatedBytesForCurrentThread () - before;

        // A quadratic hook path re-copied the pending frame on every attribute change (hundreds of MB here).
        Assert.InRange (allocated, 0, 16 * 1024 * 1024);
        Assert.Equal (10_000, output.AttributeCalls);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void LegacyAttributeHook_SurrogatePairAcrossChunks_IsPreserved ()
    {
        SplitSurrogateOutput output = new ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        output.Write (buffer);

        Assert.Equal (new string ('a', 15) + "😀X", output.Written.ToString ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void FailedUnixFrame_CanBeRetriedWithoutRedrawingBuffer ()
    {
        bool fail = true;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                fail = false;
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        Assert.Throws<IOException> (() => output.Write (buffer));
        Assert.True (buffer.DirtyLines [0]);
        Assert.True (buffer.Contents! [0, 0].IsDirty);

        output.Write (buffer);

        Assert.Single (writes);
        Assert.Contains ("X", writes [0]);
        Assert.False (buffer.DirtyLines [0]);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void ConcreteLegacyStringSinks_ReceiveTextAndImages ()
    {
        LegacyAnsiOutput ansi = new ();
        LegacyNetOutput net = new ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("Ω");
        SixelToRender sixel = new () { SixelData = "IMAGE", ScreenPosition = new (0, 0) };
        ansi.GetSixels ().Enqueue (sixel);
        ansi.Write (buffer);
        buffer.Move (0, 0);
        buffer.AddStr ("Ω");
        sixel.IsDirty = true;
        net.GetSixels ().Enqueue (sixel);
        net.Write (buffer);

        Assert.Contains ("Ω", ansi.Written.ToString ());
        Assert.Contains ("IMAGE", ansi.Written.ToString ());
        Assert.Contains ("Ω", net.Written.ToString ());
        Assert.Contains ("IMAGE", net.Written.ToString ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false)]
    [InlineData (true)]
    public void FailedFrame_RetriesRasterAndSixel (bool sourceCrop)
    {
        bool fail = true;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                fail = false;
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        }) { UseKittyGraphics = true };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (2, 1);
        RasterImageCommand image = new ()
        {
            Id = "retry-image",
            Pixels = new Color [1, 1] { { new (255, 0, 0) } },
            DestinationCells = new (1, 0, 1, 1),
            SourceRect = sourceCrop ? new Rectangle (0, 0, 1, 1) : null
        };
        buffer.AddRasterImage (image);
        SixelToRender sixel = new () { SixelData = "\u001bPq#0~\u001b\\", ScreenPosition = new (0, 0) };
        output.GetSixels ().Enqueue (sixel);

        Assert.Throws<IOException> (() => output.Write (buffer));
        Assert.True (image.IsDirty);
        Assert.True (sixel.IsDirty);
        output.Write (buffer);

        string actual = string.Concat (writes);
        Assert.Contains (sourceCrop ? "a=t" : "a=T", actual);
        Assert.Contains (sixel.SixelData, actual);
        Assert.Contains ("a=d", actual);
        Assert.False (image.IsDirty);
        Assert.False (sixel.IsDirty);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false)]
    [InlineData (true)]
    public void FailedFrame_RetriesVanishedKittyDeletion (bool sourceCrop)
    {
        bool fail = false;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (fail)
            {
                fail = false;
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        }) { UseKittyGraphics = true };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddRasterImage (new RasterImageCommand
        {
            Id = "vanished-image",
            Pixels = new Color [1, 1] { { new (255, 0, 0) } },
            DestinationCells = new (0, 0, 1, 1),
            SourceRect = sourceCrop ? new Rectangle (0, 0, 1, 1) : null
        });
        output.Write (buffer);
        writes.Clear ();
        buffer.RemoveRasterImage ("vanished-image");
        fail = true;

        Assert.Throws<IOException> (() => output.Write (buffer));
        output.Write (buffer);

        Assert.Contains ("a=d", string.Concat (writes));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void FailedFrame_PreservesInlineCleanCellsAndWideGrapheme ()
    {
        bool fail = true;
        AnsiOutput output = new (_ => !fail);
        OutputBufferImpl buffer = new () { InlineMode = true };
        buffer.SetSize (4, 3);
        buffer.Move (1, 1);
        buffer.AddStr ("中");
        bool [,] dirty = new bool [3, 4];
        for (int row = 0; row < 3; row++)
        {
            for (int col = 0; col < 4; col++)
            {
                dirty [row, col] = buffer.Contents! [row, col].IsDirty;
            }
        }

        Assert.Throws<IOException> (() => output.Write (buffer));
        for (int row = 0; row < 3; row++)
        {
            for (int col = 0; col < 4; col++)
            {
                Assert.Equal (dirty [row, col], buffer.Contents! [row, col].IsDirty);
            }
        }

        Assert.False (buffer.DirtyLines [0]);
        Assert.True (buffer.DirtyLines [1]);
        Assert.False (buffer.DirtyLines [2]);
        fail = false;
        output.Write (buffer);
        Assert.Contains ("中", output.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void FrameAtVisibleCursorPosition_StillRenders ()
    {
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        });
        output.SetCursor (new Cursor { Position = new (0, 0) });
        writes.Clear ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        output.Write (buffer);

        Assert.Contains ("X", string.Concat (writes));
        Assert.False (buffer.DirtyLines [0]);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (128 * 1024, 16)]
    [InlineData (1024 * 1024, 3)]
    public void ManySixels_BoundStagingAndKeepOrder (int payloadSize, int count)
    {
        int writes = 0;
        int total = 0;
        int largest = 0;
        AnsiOutput output = new (bytes =>
        {
            writes++;
            total += bytes.Length;
            largest = Math.Max (largest, bytes.Length);
            return true;
        }) { CaptureOutput = false };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        for (int index = 0; index < count; index++)
        {
            output.GetSixels ().Enqueue (new SixelToRender
            {
                SixelData = new string ('q', payloadSize),
                ScreenPosition = new (0, 0)
            });
        }

        output.Write (buffer);

        Assert.True (writes >= 3);
        Assert.InRange (largest, 1, Utf8Buffer.RetainedCapacityLimit);
        Assert.True (total > 2 * 1024 * 1024);
        Assert.InRange (output.RetainedWriteBufferBytes, 0, Utf8Buffer.RetainedCapacityLimit * 2);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void WindowsVT_ShortWrites_RetryExactUtf8Tail ()
    {
        List<byte> received = [];
        WindowsVTOutputHelper helper = new ((ReadOnlySpan<byte> bytes, out uint written, out int error) =>
        {
            written = (uint)Math.Min (2, bytes.Length);
            error = 0;
            received.AddRange (bytes [..(int)written].ToArray ());
            return true;
        });
        byte [] expected = Encoding.UTF8.GetBytes ("A😀中Z");

        helper.Write (expected);

        Assert.Equal (expected, received.ToArray ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false, 0)]
    [InlineData (true, 0)]
    [InlineData (true, 10)]
    public void WindowsVT_FailureOrInvalidProgress_Throws (bool succeeded, int count)
    {
        WindowsVTOutputHelper helper = new ((ReadOnlySpan<byte> _, out uint written, out int error) =>
        {
            written = (uint)count;
            error = 5;
            return succeeded;
        });

        if (!succeeded)
        {
            Assert.Throws<Win32Exception> (() => helper.Write (new byte [2]));
            return;
        }

        Assert.Throws<IOException> (() => helper.Write (new byte [2]));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void AnsiLegacyAttributeHook_FlushesBeforePhysicalColorChange ()
    {
        List<string> events = [];
        PhysicalAttributeOutput output = new (events);
        OutputBufferImpl buffer = new ();
        buffer.SetSize (2, 1);
        buffer.CurrentAttribute = new (new Color (1, 0, 0), Color.Black);
        buffer.AddStr ("A");
        buffer.CurrentAttribute = new (new Color (2, 0, 0), Color.Black);
        buffer.AddStr ("B");

        output.Write (buffer);

        Assert.Equal (["attribute:1", "text:A", "attribute:2", "text:B"], events);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void FailedStyledLinkedFrame_RetryResetsTerminalStateAndCaptureMatchesBytes ()
    {
        int attempts = 0;
        List<string> writes = [];
        AnsiOutput output = new (bytes =>
        {
            if (++attempts <= 2)
            {
                return false;
            }

            writes.Add (Encoding.UTF8.GetString (bytes));
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (2, 1);
        buffer.CurrentAttribute = new (Color.Red, Color.Black) { Style = TextStyle.Bold | TextStyle.Italic };
        buffer.CurrentUrl = "https://example.org/路径";
        buffer.AddStr ("éX");

        Assert.Throws<IOException> (() => output.Write (buffer));
        Assert.Throws<IOException> (() => output.Write (buffer));
        output.Write (buffer);

        string actual = Assert.Single (writes);
        Assert.StartsWith ("\u001b\\" + EscSeqUtils.OSC_EndHyperlink () + EscSeqUtils.CSI_ResetAttributes, actual);
        Assert.Contains ("https://example.org/路径", actual);
        Assert.Contains ("éX", actual);
        Assert.EndsWith (EscSeqUtils.OSC_EndHyperlink (), actual);
        Assert.Equal (actual, output.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void WindowsVT_PartialWrite_DoesNotAllocateTailArray ()
    {
        int calls = 0;
        WindowsVTOutputHelper helper = new ((ReadOnlySpan<byte> _, out uint written, out int error) =>
        {
            calls++;
            written = 1;
            error = 0;
            return true;
        });
        byte [] backing = new byte [1024 * 1024];
        helper.Write (backing.AsSpan (0, 2));
        calls = 0;
        long before = GC.GetAllocatedBytesForCurrentThread ();

        helper.Write (backing.AsSpan (0, 2));

        long allocated = GC.GetAllocatedBytesForCurrentThread () - before;
        Assert.Equal (2, calls);
        Assert.InRange (allocated, 0, 128);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void StreamingFrame_LateFailure_RetriesTextAndLargeSixel ()
    {
        int attempts = 0;
        int textWrites = 0;
        int imageBytes = 0;
        AnsiOutput output = new (bytes =>
        {
            if (++attempts == 2)
            {
                return false;
            }

            if (bytes.IndexOf ((byte)'X') >= 0) textWrites++;
            foreach (byte value in bytes)
            {
                if (value == (byte)'q') imageBytes++;
            }
            return true;
        }) { CaptureOutput = false };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");
        SixelToRender sixel = new ()
        {
            SixelData = new string ('q', 2 * Utf8Buffer.RetainedCapacityLimit),
            ScreenPosition = new (0, 0)
        };
        output.GetSixels ().Enqueue (sixel);

        Assert.Throws<IOException> (() => output.Write (buffer));
        Assert.Equal (1, textWrites);
        Assert.True (buffer.Contents! [0, 0].IsDirty);
        Assert.True (sixel.IsDirty);
        int previouslyWrittenImageBytes = imageBytes;
        Assert.True (previouslyWrittenImageBytes > 0);
        output.Write (buffer);

        Assert.Equal (2, textWrites);
        Assert.Equal (previouslyWrittenImageBytes + sixel.SixelData.Length, imageBytes);
        Assert.False (buffer.DirtyLines [0]);
        Assert.False (sixel.IsDirty);
    }

    private sealed class PhysicalAttributeOutput : AnsiOutput
    {
        private readonly List<string> _events;

        public PhysicalAttributeOutput (List<string> events) : base (bytes =>
        {
            string text = Encoding.UTF8.GetString (bytes);
            if (text.Contains ('A')) events.Add ("text:A");
            if (text.Contains ('B')) events.Add ("text:B");
            return true;
        }) => _events = events;

        protected override void AppendOrWriteAttribute (StringBuilder output,
                                                        Terminal.Gui.Drawing.Attribute attr,
                                                        TextStyle redrawTextStyle)
        {
            Write (output);
            output.Clear ();
            _events.Add ($"attribute:{attr.Foreground.R}");
        }
    }

    private sealed class LegacyAnsiOutput : AnsiOutput
    {
        public StringBuilder Written { get; } = new ();
        protected override void Write (StringBuilder output) => Written.Append (output);
    }

    private sealed class LegacyNetOutput : NetOutput
    {
        public StringBuilder Written { get; } = new ();
        protected override void Write (StringBuilder output) => Written.Append (output);
    }

    private class StringOutput : OutputBase
    {
        public StringBuilder Written { get; } = new ();

        protected override bool SetCursorPositionImpl (int screenPositionX, int screenPositionY) => true;

        protected override void Write (StringBuilder output) => Written.Append (output);
    }

    private sealed class AppendingAttributeOutput : OutputBase
    {
        public int AttributeCalls { get; private set; }

        protected override bool SetCursorPositionImpl (int screenPositionX, int screenPositionY) => true;

        protected override void Write (StringBuilder output) { }

        protected override void AppendOrWriteAttribute (StringBuilder output,
                                                        Terminal.Gui.Drawing.Attribute attr,
                                                        TextStyle redrawTextStyle)
        {
            AttributeCalls++;
            output.Append ("\u001b[38;2;1;2;3m");
        }
    }

    private sealed class SplitSurrogateOutput : StringOutput
    {
        protected override void AppendOrWriteAttribute (StringBuilder output,
                                                        Terminal.Gui.Drawing.Attribute attr,
                                                        TextStyle redrawTextStyle)
        {
            output.Append ('a', 15);
            output.Append ('\ud83d');
            output.Append ('\ude00');
        }
    }

    private sealed class FlushingAttributeOutput : OutputBase
    {
        public List<string> Events { get; } = [];

        protected override bool SetCursorPositionImpl (int screenPositionX, int screenPositionY) => true;

        protected override void Write (StringBuilder output)
        {
            if (output.Length > 0)
            {
                Events.Add ($"text:{output}");
            }
        }

        protected override void AppendOrWriteAttribute (StringBuilder output,
                                                        Terminal.Gui.Drawing.Attribute attr,
                                                        TextStyle redrawTextStyle)
        {
            Write (output);
            output.Clear ();
            Events.Add ($"attribute:{attr.Foreground.R}");
        }
    }
}
