using System.ComponentModel;
using System.Text;

namespace DriverTests.Output;

/// <summary>Regression tests for the UTF-8 frame writer and legacy output hooks.</summary>
[Collection ("Driver Tests")]
public class OutputPathRegressionTests
{
    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void LegacyStringWriter_ReceivesRenderedCells ()
    {
        LegacyStringWriter output = new ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("Ω");

        output.Write (buffer);

        Assert.Contains ("Ω", output.Written.ToString ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void LegacyAttributeHook_IsCalledByUtf8Renderer ()
    {
        LegacyAttributeWriter output = new ();
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.CurrentAttribute = new (new Color (1, 2, 3), new Color (4, 5, 6));
        buffer.AddStr ("X");

        output.Write (buffer);

        Assert.Contains ("<attribute>X", output.Written.ToString ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_SingleRow_MatchesStringEncoderByteForByte ()
    {
        List<byte []> writes = [];
        AnsiOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (3, 1);
        buffer.CurrentAttribute = new Terminal.Gui.Drawing.Attribute (new Color (1, 2, 3), new Color (4, 5, 6))
        {
            Style = TextStyle.Bold
        };
        buffer.AddStr ("A");
        buffer.CurrentUrl = "https://example.org/路径";
        buffer.AddStr ("é");
        buffer.CurrentUrl = null;
        buffer.AddStr ("Z");

        output.Write (buffer);

        byte [] expected = Encoding.UTF8.GetBytes (EscSeqUtils.CSI_SetCursorPosition (1, 1)
                                                  + output.ToAnsi (buffer).TrimEnd ('\n'));
        Assert.Single (writes);
        Assert.Equal (expected, writes [0]);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_TwoRows_AreWrittenAsOneOrderedFrame ()
    {
        List<byte []> writes = [];
        AnsiOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (2, 2);
        buffer.Move (0, 0);
        buffer.AddStr ("AB");
        buffer.Move (0, 1);
        buffer.AddStr ("CD");

        output.Write (buffer);

        Assert.Single (writes);
        string actual = Encoding.UTF8.GetString (writes [0]);
        int firstMove = actual.IndexOf (EscSeqUtils.CSI_SetCursorPosition (1, 1), StringComparison.Ordinal);
        int firstText = actual.IndexOf ("AB", StringComparison.Ordinal);
        Assert.True (firstMove >= 0 && firstText > firstMove);
        Assert.Contains (EscSeqUtils.CSI_SetCursorPosition (2, 1) + "CD", actual);
        Assert.Equal (actual, output.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_OnlyLastDeferredCursorMoveIsSent ()
    {
        List<byte []> writes = [];
        AnsiOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (4, 1);
        output.Write (buffer);
        writes.Clear ();
        buffer.Contents! [0, 2].IsDirty = true;
        buffer.DirtyLines [0] = true;

        output.Write (buffer);

        Assert.Single (writes);
        string actual = Encoding.UTF8.GetString (writes [0]);
        Assert.StartsWith (EscSeqUtils.CSI_SetCursorPosition (1, 3), actual);
        Assert.DoesNotContain (EscSeqUtils.CSI_SetCursorPosition (1, 1), actual);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_CharWriteDuringFrame_FollowsDeferredCursorMove ()
    {
        List<byte []> writes = [];
        InjectingCursorOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        output.Write (buffer);

        Assert.Single (writes);
        string actual = Encoding.UTF8.GetString (writes [0]);
        int cursor = actual.IndexOf (EscSeqUtils.CSI_SetCursorPosition (1, 1), StringComparison.Ordinal);
        int injected = actual.IndexOf ('M');
        int cell = actual.LastIndexOf ('X');
        Assert.True (cursor >= 0 && injected > cursor && cell > injected);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_KittyHyperlinkAndSixel_KeepTheirOrder ()
    {
        List<byte []> writes = [];
        AnsiOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());
            return true;
        }) { UseKittyGraphics = true };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (3, 1);
        buffer.Clip = new Region (new Rectangle (0, 0, 3, 1));
        buffer.AddRasterImage (new RasterImageCommand
        {
            Id = "image",
            Pixels = new Color [1, 1] { { new (255, 0, 0) } },
            DestinationCells = new Rectangle (2, 0, 1, 1)
        });
        buffer.CurrentUrl = "https://example.org/路径";
        buffer.AddStr ("é");
        output.GetSixels ().Enqueue (new SixelToRender
        {
            SixelData = "\u001bPq#0~\u001b\\",
            ScreenPosition = new (0, 0)
        });

        output.Write (buffer);

        string actual = Encoding.UTF8.GetString (writes.SelectMany (bytes => bytes).ToArray ());
        int kitty = actual.IndexOf ("\u001b_G", StringComparison.Ordinal);
        int hyperlink = actual.IndexOf ("https://example.org/路径", StringComparison.Ordinal);
        int sixel = actual.IndexOf ("\u001bPq", StringComparison.Ordinal);
        Assert.True (kitty >= 0 && hyperlink > kitty && sixel > hyperlink);
        Assert.Equal (actual, output.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_FailedFrame_DiscardsPendingCursorMoves ()
    {
        List<byte []> writes = [];
        bool fail = true;
        AnsiOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());

            if (!fail)
            {
                return true;
            }

            fail = false;
            return false;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        Assert.Throws<IOException> (() => output.Write (buffer));
        output.Write ("Z".AsSpan ());

        Assert.Equal (2, writes.Count);
        Assert.Equal ("Z", Encoding.UTF8.GetString (writes [1]));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_RenderException_DoesNotSendDeferredCursorMove ()
    {
        List<byte []> writes = [];
        ThrowingCursorOutput output = new (bytes =>
        {
            writes.Add (bytes.ToArray ());
            return true;
        });
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        Assert.Throws<InvalidOperationException> (() => output.Write (buffer));
        Assert.Empty (writes);

        output.Write ("Z".AsSpan ());
        Assert.Single (writes);
        Assert.Equal ("Z", Encoding.UTF8.GetString (writes [0]));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_UnexpectedWriterException_IsNotHidden ()
    {
        AnsiOutput output = new (_ => throw new InvalidOperationException ("writer bug"));
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");

        Assert.Throws<InvalidOperationException> (() => output.Write (buffer));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Theory]
    [InlineData (false, 0, 1, 5)]
    [InlineData (true, 0, 1, 0)]
    public void WindowsWriteResult_RejectsFailureAndPartialWrite (bool succeeded,
                                                                   uint written,
                                                                   uint expected,
                                                                   int error)
    {
        if (!succeeded)
        {
            Assert.Throws<Win32Exception> (() => WindowsOutput.ValidateConsoleWriteResult (succeeded, written, expected, error));
            return;
        }

        Assert.Throws<IOException> (() => WindowsOutput.ValidateConsoleWriteResult (succeeded, written, expected, error));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void NetAndWindowsByteSinks_CaptureUnicodeWithoutAStringWrite ()
    {
        byte [] encoded = Encoding.UTF8.GetBytes ("Aé中😀");
        ExposedNetOutput net = new () { CaptureOutput = true };
        ExposedWindowsOutput windows = new () { CaptureOutput = true };

        net.WriteBytes (encoded);
        windows.WriteBytes (encoded);

        Assert.Equal ("Aé中😀", net.GetLastOutput ());
        Assert.Equal ("Aé中😀", windows.GetLastOutput ());
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void UnixRaw_LargeSixel_DoesNotRetainLargeWriteBuffers ()
    {
        int bytesWritten = 0;
        AnsiOutput output = new (bytes =>
        {
            bytesWritten += bytes.Length;
            return true;
        }) { CaptureOutput = false };
        OutputBufferImpl buffer = new ();
        buffer.SetSize (1, 1);
        buffer.AddStr ("X");
        output.GetSixels ().Enqueue (new SixelToRender
        {
            SixelData = new string ('q', 4 * 1024 * 1024),
            ScreenPosition = new (0, 0)
        });

        output.Write (buffer);
        buffer.Move (0, 0);
        buffer.AddStr ("Y");
        output.Write (buffer);

        Assert.True (bytesWritten >= 4 * 1024 * 1024);
        Assert.InRange (output.RetainedWriteBufferBytes, 0, Utf8Buffer.RetainedCapacityLimit * 2);
        Assert.Equal (string.Empty, output.GetLastOutput ());
    }

    private class LegacyStringWriter : OutputBase
    {
        public StringBuilder Written { get; } = new ();

        protected override bool SetCursorPositionImpl (int screenPositionX, int screenPositionY) => true;

        protected override void Write (StringBuilder output) => Written.Append (output);
    }

    private sealed class LegacyAttributeWriter : LegacyStringWriter
    {
        protected override void AppendOrWriteAttribute (StringBuilder output,
                                                        Terminal.Gui.Drawing.Attribute attr,
                                                        TextStyle redrawTextStyle) => output.Append ("<attribute>");
    }

    private sealed class InjectingCursorOutput : AnsiOutput
    {
        private bool _injected;

        public InjectingCursorOutput (UnixWriter writer) : base (writer) { }

        protected override bool SetCursorPositionImpl (int col, int row)
        {
            bool moved = base.SetCursorPositionImpl (col, row);

            if (_injected)
            {
                return moved;
            }

            _injected = true;
            Write ("M".AsSpan ());
            return moved;
        }
    }

    private sealed class ThrowingCursorOutput : AnsiOutput
    {
        private bool _throw = true;

        public ThrowingCursorOutput (UnixWriter writer) : base (writer) { }

        protected override bool SetCursorPositionImpl (int col, int row)
        {
            bool moved = base.SetCursorPositionImpl (col, row);

            if (_throw)
            {
                _throw = false;
                throw new InvalidOperationException ("render failure");
            }

            return moved;
        }
    }

    private sealed class ExposedNetOutput : NetOutput
    {
        public void WriteBytes (ReadOnlySpan<byte> bytes) => Write (bytes);
    }

    private sealed class ExposedWindowsOutput : WindowsOutput
    {
        public void WriteBytes (ReadOnlySpan<byte> bytes) => Write (bytes);
    }
}
