using System.Runtime.InteropServices;
using Terminal.Gui.Drivers;

namespace DriverTests;

/// <summary>
///     Tests for <see cref="UnixIOHelper"/> polling semantics on Unix-like platforms.
/// </summary>
[Collection ("Driver Tests")]
public class UnixIOHelperTests
{
    [DllImport ("libc", SetLastError = true)]
    private static extern int pipe (int [] pipefd);

    [DllImport ("libc", SetLastError = true)]
    private static extern int close (int fd);

    [Fact]
    public void TryWriteAll_ReturnsFalse_WhenWriteReturnsZero ()
    {
        var calls = 0;
        byte [] payload = [0x41, 0x42];

        bool result = UnixIOHelper.TryWriteAll (1,
                                                payload,
                                                (_, _) =>
                                                {
                                                    calls++;

                                                    return 0;
                                                });

        Assert.False (result);
        Assert.Equal (1, calls);
    }

    [Fact]
    public void TryWriteAll_RetriesUntilAllBytesWritten ()
    {
        List<int> counts = [];
        List<byte> firstBytes = [];
        byte [] payload = [0x41, 0x42, 0x43];

        bool result = UnixIOHelper.TryWriteAll (1,
                                                payload,
                                                (_, buffer) =>
                                                {
                                                    counts.Add (buffer.Length);
                                                    firstBytes.Add (buffer [0]);

                                                    return 1;
                                                });

        Assert.True (result);
        Assert.Equal ([3, 2, 1], counts);
        Assert.Equal ([0x41, 0x42, 0x43], firstBytes);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void TryWriteAll_PartialWriteOfSmallSpan_DoesNotCopyLargeBackingArray ()
    {
        byte [] backing = new byte [1_000_000];
        backing [0] = (byte)'A';
        backing [1] = (byte)'B';
        int calls = 0;
        int firstCount = 0;
        int secondCount = 0;
        byte secondByte = 0;
        UnixIOHelper.WriteBytes writer = (_, remaining) =>
        {
            if (calls == 0)
            {
                firstCount = remaining.Length;
            }
            else
            {
                secondCount = remaining.Length;
                secondByte = remaining [0];
            }

            calls++;
            return 1;
        };

        UnixIOHelper.TryWriteAll (1, backing.AsSpan (0, 2), writer);
        calls = 0;
        long before = GC.GetAllocatedBytesForCurrentThread ();
        bool result = UnixIOHelper.TryWriteAll (1, backing.AsSpan (0, 2), writer);
        long allocated = GC.GetAllocatedBytesForCurrentThread () - before;

        Assert.True (result);
        Assert.Equal (2, calls);
        Assert.Equal (2, firstCount);
        Assert.Equal (1, secondCount);
        Assert.Equal ((byte)'B', secondByte);
        Assert.InRange (allocated, 0, 1024);
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void TryWriteAll_RejectsWriterThatClaimsMoreThanRemaining ()
    {
        byte [] payload = [0x41];

        Assert.False (UnixIOHelper.TryWriteAll (1, payload, (_, _) => 2));
    }

    // CoPilot - GPT-6 (generated by Codex)
    [Fact]
    public void TryWriteAll_NativeSpanWrite_UsesOnlyRequestedBytes ()
    {
        if (OperatingSystem.IsWindows ())
        {
            return;
        }

        int [] pipeFds = new int [2];
        Assert.Equal (0, pipe (pipeFds));

        try
        {
            byte [] backing = new byte [1_000_000];
            backing [0] = (byte)'A';
            backing [1] = (byte)'B';
            backing [2] = (byte)'C';

            Assert.True (UnixIOHelper.TryWriteAll (pipeFds [1], backing.AsSpan (0, 2), UnixIOHelper.WriteSpan));

            byte [] received = new byte [2];
            Assert.Equal (2, UnixIOHelper.read (pipeFds [0], received, received.Length));
            Assert.Equal ([(byte)'A', (byte)'B'], received);
        }
        finally
        {
            close (pipeFds [0]);
            close (pipeFds [1]);
        }
    }

    [Fact]
    // Copilot
    public void IsInputAvailable_ReturnsTrue_WhenPollReportsReadableData ()
    {
        if (OperatingSystem.IsWindows ())
        {
            return;
        }

        int [] pipeFds = new int [2];
        Assert.Equal (0, pipe (pipeFds));

        try
        {
            byte [] payload = [0x41];
            Assert.Equal (1, UnixIOHelper.write (pipeFds [1], payload, payload.Length));

            UnixIOHelper.Pollfd [] pollMap =
            [
                new ()
                {
                    fd = pipeFds [0],
                    events = (short)UnixIOHelper.Condition.PollIn
                }
            ];

            Assert.True (UnixIOHelper.IsInputAvailable (pollMap, 0));
        }
        finally
        {
            close (pipeFds [0]);
            close (pipeFds [1]);
        }
    }

    [Fact]
    // Copilot
    public void IsInputAvailable_ReturnsFalse_WhenPollReportsNonReadableEvent ()
    {
        if (OperatingSystem.IsWindows ())
        {
            return;
        }

        int [] pipeFds = new int [2];
        Assert.Equal (0, pipe (pipeFds));

        try
        {
            Assert.Equal (0, close (pipeFds [0]));

            UnixIOHelper.Pollfd [] pollMap =
            [
                new ()
                {
                    fd = pipeFds [0],
                    events = (short)UnixIOHelper.Condition.PollIn
                }
            ];

            Assert.False (UnixIOHelper.IsInputAvailable (pollMap, 0));
        }
        finally
        {
            close (pipeFds [1]);
        }
    }
}
